services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  discountserver:
    build:
      context: ./
      dockerfile: DISCOUNT.Server/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - redis

  discountclient:
    build:
      context: ./DISCOUNT.Client
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - discountserver

volumes:
  redis-data:
