services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  discountserver:
    build:
      context: ./
      dockerfile: DISCOUNT.Server/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - redis

  discountclient:
    build:
      context: ./
      dockerfile: DISCOUNT.Client/Dockerfile
    ports:
      - "6000:6000"
    depends_on:
      - discountserver

volumes:
  redis-data: